config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users, only: [:show] do
    resources :collaborators, only: [:new, :create, :delete, :destroy]
  end
  
  resources :wikis do
    resources :collaborators, only: [:new, :create, :delete, :destroy]
    collection do
      post :bulk_collaborators_update
    end
  end
  
  resources :charges, only: [:new, :create, :edit, :update]
  
  get 'welcome/index'
  root to: 'welcome#index'

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  has_many :users, through: :collaborators
  has_many :collaborators, dependent: :destroy
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def show
    @wiki = Wiki.find(params[:id])
  end
  
  def index
    @wikis = policy_scope(Wiki)
  end
  
  def new
    @wiki = Wiki.new
  end
  
  def create
    @wiki = current_user.wikis.build(wiki_params)
    @wiki.user_id = current_user.id
    
    if @wiki.save
      @wiki.collaborators.create(:user_id => current_user.id, :wiki_id => @wiki.id)
      flash[:notice] = "Wiki has been created"
      redirect_to [@wiki]
    else
      flash[:error] = "Error occurred creating wiki, please try again"
      render :new
    end    
  end
  
  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to current_user
    else
      flash[:error] = "There was an issue deleting the wiki"
      render :show
    end
  end
  
  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    
    @wiki.assign_attributes(wiki_params)
    
    if @wiki.update(wiki_params)
      flash[:notice] = "Wiki has been updated"
      redirect_to [@wiki]
    else
      flash[:error] = "Error occurred updating wiki, please try again"
      render :edit
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki 
  end
  
  def bulk_collaborators_update
    @wiki = Wiki.find(params[:wiki_id])
    
    if params[:email_addresses] != ""
      @user_email_addresses = params[:email_addresses].split(/,\s*/)
      @user_email_addresses.each do |user|
        if User.exists?(email: user)
          @new_user = User.where(email: user)
          if !@wiki.collaborators.exists?(user_id: @new_user)
            @wiki.collaborators.create(user_id: @new_user.ids[0], wiki_id: @wiki.id)
          end
        else
          flash[:error] = "User does not exist!"
        end
      end
    end
    redirect_to wiki_path(@wiki.id)
  end
  
  private
  
  def wiki_params
    params.require(:wiki).permit(:title,:body,:private,:user_id)
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_form.html.erb
<%= form_for [wiki] do |f| %>
  <div class='form_group'>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form_control', placeholder: 'Enter wiki name' %>
  </div>
  <div class='field'>
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form_control', placeholder: 'Enter wiki body' %>
  </div>
  <% if current_user.admin? || current_user.premium? %>
    <div class='form_group'>
      <%= f.label :private %>
      <%= f.check_box :private %> Private Wiki
    </div>
  <% end %>
  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/wikis/_wiki.html.erb
<div class="row">
  <div class="col-md-6"><%= link_to wiki.title, wiki_path(wiki) %></div>
  <% if current_user != nil %>  
    <% if policy(wiki).edit? %>
      <div class="col-md-3"><%= link_to "Edit", edit_wiki_path(wiki.id) %></div>
    <% end %>
    <% if policy(wiki).destroy? %>
      <div class="col-md-3"><%= link_to "Delete", [wiki], method: :delete %></div>
    <% end %>
  <% end %>
</div>

app/views/wikis/_wikis.html.erb
<div class="panel-spacing">
  <div class="panel panel-default">
    <div class="panel-heading"><%= page_title %></div>
    <div class="panel-body">
      <div class="row">
          <div class="col-md-6">Title</div>
      </div>
      <% wikis.each do |wiki| %>
        <%= render partial: 'wikis/wiki', locals: {wiki: wiki} %>
      <% end %>
    </div>
  </div>
</div>
<% if current_user != nil %>
  <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
<% end %>

app/views/wikis/edit.html.erb
<h4>Update Wiki</h4>
<%= render partial: 'wikis/form', locals: {current_user: current_user, wiki: @wiki} %>

app/views/wikis/index.html.erb
<%= render partial: 'wikis/wikis', locals: {wikis: @wikis, page_title: "All Wikis"} %>

app/views/wikis/new.html.erb
<h4>Create a new wiki</h4>
<%= render partial: 'wikis/form', locals: {current_user: current_user, wiki: @wiki} %>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>
<h4><%= markdown(@wiki.body) %></h4>

<% if current_user != nil and current_user.id == @wiki.user_id %>
  <%= form_tag bulk_collaborators_update_wikis_path, method: :post do %>
    <div class="panel panel-default">
      <div class="panel-heading">Wiki Collaborators</div>
      <div class="panel-body">
        <div class="row">
            <div class="col-md-6">User Email</div>
            <div class="col-md-6">Collaborator Access</div>
        </div>
        <% @wiki.collaborators.each do |collaborator| %>
          <% if collaborator.user_id != @wiki.user_id %>
            <div class="col-md-6">
              <%= collaborator.user.email if collaborator.user %>
            </div>
            <div class="col-md-6">
              <%= link_to "remove", wiki_collaborator_path(@wiki,collaborator), method: :delete %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <br>
    <h4>Enter comma seperate email addresses of new collaborators</h4>
    <%= text_field_tag "email_addresses" %>
    <%= hidden_field_tag "wiki_id", @wiki.id %>
    <br><br>
    <%= submit_tag "Update Collaborators" %>
  <% end %>
<% end %>