config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users, only: [:show] do
    resources :collaborators, only: [:new, :create, :delete, :destroy]
  end
  
  resources :wikis do
    resources :collaborators, only: [:new, :create, :delete, :destroy]
    collection do
      post :bulk_collaborators_update
    end
  end
  
  resources :charges, only: [:new, :create, :edit, :update]
  
  get 'welcome/index'
  root to: 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <ul class="nav nav-tabs">
    <li><%= link_to "Blocipedia", root_path %></li>
    <li><%= link_to "Wikis", wikis_path %></li>
    <div class="pull-right">
      <% if user_signed_in? %>
        Signed in as: <strong><%= current_user.email %></strong>
        <%= link_to 'User Profile', user_path(current_user.id), :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
      <% else %>
        <%= link_to 'Sign In', new_user_session_path, :class => 'navbar-link' %>
      <% end %>
    </div>
  </ul>
  <div class="flash">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
  </div>
  <%= yield %>
</div>
</body>
</html>